#######################################################
#~                                                   ~#
#~         Default ModHelp Configuration File        ~#
#~             Version 1.0.0 by AzubuSan             ~#
#~                                                   ~#
#######################################################

#There is literally nothing in here right now due to the fact that I switched to properties files
#~Azubu